change questionnaire buttons to radio
echanlee/PP-friends pull request #11
Opened 2020-11-04 17:05 UTC by mnsison

Questionnaire choices changed from buttons to radio to allow users to change their responses while answering questionnaire

2020-11-04 18:23 UTC, wclui approved these changes

2020-11-04 22:21 UTC, echanlee requested changes
remove all the binary files

2020-11-04 22:21 UTC, echanlee commented on src/Questionnaire.js
> +    console.log(this.state.response);
remove

2020-11-07 16:43 UTC, echanlee approved these changes

2020-11-09 14:23 UTC, merged