Messaging ui
echanlee/PP-friends pull request #28
Opened 2020-11-18 21:56 UTC by chalynpai

![messagingUI pr](https://user-images.githubusercontent.com/48136962/99592980-f40dc400-29be-11eb-819b-82c9122f050e.png)

2020-11-18 22:59 UTC, echanlee commented
I think it would look nice if the typing message box was within the messages box

2020-11-18 23:02 UTC, echanlee requested changes

2020-11-18 23:02 UTC, echanlee commented on src/Messages.js
> +            :
can you reformat indentation to make it more clear which ternary statement the `:` belongs to

2020-11-19 04:37 UTC, jj7lin commented on src/Messages.css
> +    color: white;;
Maybe use a different color for the time text? It isn't as clear in the coral message box so it's harder to see

2020-11-19 04:39 UTC, jj7lin requested changes
some minor changes, but overall looks good

2020-11-19 04:39 UTC, jj7lin commented on src/Messages.css
> +    color: white;;
Can the button align to the right of the conversation container so they're better spaced out?

2020-11-19 05:36 UTC, echanlee approved these changes

2020-11-19 17:47 UTC, jj7lin approved these changes

2020-11-19 18:44 UTC, merged