Location match
echanlee/PP-friends pull request #51
Opened 2020-12-02 23:21 UTC by mtlssica

Add functionality that now the potential matches show up on swiping pages will obey the max distance set by both current and shown users:  if the distance between them exceeds either of their max distance set. 
Distance calculated based on longitude and latitude assuming Earth is spherical using simplified Haversine formula (ignoring altitude as well).

Tested user:
id 25, 59 and 71
Tested cases: 
1- current user not giving location
2- potential match not giving location 
3- distance between users exceeds max distance set by current user
4- distance between exceeds max distance set by shown user
5- distance within the range of max distance
6- no potential match

2020-12-02 23:35 UTC, echanlee requested changes

2020-12-02 23:35 UTC, echanlee commented on server/SwipeDecision.py
>              potentialListId = [i[0] for i in cursor.fetchall()]
maybe when you execute the potential match query retrieve the user id and the locations so you don't need to call the database gain later

2020-12-02 23:35 UTC, echanlee commented on server/SwipeDecision.py
> +            newPotentialMatchList = []
I think you should put the finding the potential list based on the location into a new method that returns the new potential mist list

2020-12-02 23:35 UTC, echanlee commented on server/SwipeDecision.py
> +                    for i in currentUserLocation:
should this be in a for loop? Aren't we just looking at one value

2020-12-02 23:35 UTC, echanlee commented on server/SwipeDecision.py
> +
can you put the calculation in a separate method to make it more readible

2020-12-02 23:35 UTC, echanlee commented on server/SwipeDecision.py
> +                            findMaxDistance = "SELECT maxDistance FROM Profile WHERE userId = %s"
when you look for the current user longitude and latitude you should get their max distance and store that somewhere as well. Try to minimize the number of database calls

2020-12-03 01:36 UTC, echanlee requested changes

2020-12-03 01:36 UTC, echanlee commented on server/SwipeDecision.py
> +                        potentialMatchLongitude = readLocation(potentialMatchLocation)[0]
why would you call the method three times when you can just call it once and store the various indexes into different variables

2020-12-03 01:36 UTC, echanlee commented on server/SwipeDecision.py
>              potentialListId = [i[0] for i in cursor.fetchall()]
instead of just retrieving the ids retrieve their ids AND their longatide and latitude so you don't have to do it again

2020-12-03 01:36 UTC, echanlee commented on server/SwipeDecision.py
> +            if(len(potentialListId) != 0):
if length of `potentialListId` id equals 0 why would you set `newPotentialMatchList = potentialListId `.  Both lists are already `[]` so the else statement for this doesn't do anything. You can remove it

2020-12-03 01:36 UTC, echanlee commented on server/SwipeDecision.py
> +                currentUserLongitude = readLocation(currentUserLocation)[0]
I'm not sure why you would need a separate method to do this. It doesn't decrease the number of lines you're writing and it doesn't split up the code nicely.

2020-12-03 01:36 UTC, echanlee commented on server/SwipeDecision.py
> +                            else:
if this else does not do anything remove it

2020-12-03 01:36 UTC, echanlee commented on server/SwipeDecision.py
> +                            if ((distance <= currentUserMaxDistance) & (distance <= potentialMatchMaxDistance)):
you need two &. should be `((distance <= currentUserMaxDistance) && (distance <= potentialMatchMaxDistance))`

2020-12-03 01:36 UTC, echanlee commented on server/SwipeDecision.py
> +            if(len(potentialListId) != 0):
Put all the code within this if statement into a method called `getMatchesWithinMaxDistance` and add `newPotentialMatchList = getMatchesWithinMaxDistance(...)` within this if statement

2020-12-03 06:05 UTC, echanlee requested changes

2020-12-03 06:05 UTC, echanlee commented on server/SwipeDecision.py
> +getPotentialMatchList(25)
remove this

2020-12-03 06:07 UTC, echanlee approved these changes

2020-12-05 02:24 UTC, wclui approved these changes

2020-12-05 02:27 UTC, merged